version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  apt_packages:
    - clang
  jobs:
    pre_build:
      - CC=clang CXX=clang++ python -m pip install -v libshortfin/

python:
  install:
    - requirements: libshortfin/docs/requirements.txt

sphinx:
  configuration: libshortfin/docs/conf.py
