[build-system]
requires = [
    "cmake>=3.29",
    "setuptools>=61.0",
    "wheel",
    "nanobind>=2.0",
    "ninja",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = [
    "-ra",
    "--import-mode=importlib",
]
testpaths = [
    "tests",
]
