version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - python -m pip install -v shortfin/

python:
  install:
    - requirements: shortfin/docs/requirements.txt

sphinx:
  configuration: shortfin/docs/conf.py
