name: CI - sharktank

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/workflows/ci-sharktank.yml'
      - 'sharktank/**'
      - '*requirements*.txt'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/ci-sharktank.yml'
      - 'sharktank/**'
      - '*requirements*.txt'

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: "Unit Tests and Type Checking"
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
