# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - sharktank and shortfin

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_llama:
    name: "Integration Tests - Shortfin LLM Server"
    strategy:
      matrix:
        version: [3.11]
      fail-fast: false
    runs-on: llama-mi300x-1
    defaults:
      run:
        shell: bash
    env:
      PIP_CACHE_DIR: "${{ github.workspace }}/.pip-cache"
    steps:
      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: Cache Pip Packages
        uses: actions/cache@v4
        id: cache-pip
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('*requirements.txt') }}

      - name: Install pip deps
        run: |
          python -m pip install --no-compile --upgrade pip
          # Note: We install in three steps in order to satisfy requirements
          # from non default locations first. Installing the PyTorch CPU
          # wheels saves multiple minutes and a lot of bandwidth on runner setup.
          pip install --no-compile -r pytorch-cpu-requirements.txt
          pip install --no-compile -f https://iree.dev/pip-release-links.html --src deps \
            -e "git+https://github.com/iree-org/iree-turbine.git#egg=iree-turbine"
          pip install --no-compile -r requirements.txt -e sharktank/ shortfin/

          # Try with the latest nightly releases, not what iree-turbine pins.
          # We could also pin to a known working or stable version.
          # This should eventually stabilize. Do the best we can for now.
          pip install -f https://iree.dev/pip-release-links.html --upgrade \
            iree-compiler \
            iree-runtime \
            "numpy<2.0"

      - name: Run shortfin LLM Server Integration Test
        run: pytest -v build_tools/integration_tests/cpu_llm_server_test.py
