name: CI - Tuner

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci-tuner.yml'
      - 'tuner/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-tuner.yml'
      - 'tuner/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.10.12'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tuner/requirements-dev.txt

      - name: Install tuner dependencies
        run: |
          pip install -r tuner/requirements-tuner.txt
          python -m pip install \
            --find-links https://iree.dev/pip-release-links.html \
            --upgrade \
            iree-compiler iree-runtime

      - name: Run tuner tests
        run: pytest tuner/
