name: CI - Tuner

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre-commit-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sharktank/sharktank/tools/tuner/requirements-dev.txt

      - name: Run pre-commit test
        run: pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Install tuner dependencies
        run: |
          pip install -r sharktank/sharktank/tools/tuner/requirements-tuner.txt
          python -m pip install \
            --find-links https://iree.dev/pip-release-links.html \
            --upgrade \
            iree-compiler iree-runtime

      - name: Run pytest
        working-directory: sharktank/sharktank/tests/tuner
        run: |
          python -m pytest
