# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - shortfin

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci_linux_x64-libshortfin.yml'
      - 'shortfin/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci_linux_x64-libshortfin.yml'
      - 'shortfin/**'

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  IREE_REPO_DIR: ${{ github.workspace }}/iree
  LIBSHORTFIN_DIR: ${{ github.workspace }}/shortfin/

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install clang lld cmake ninja-build

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: false

    - name: Checkout IREE repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: iree-org/iree
        path: ${{ env.IREE_REPO_DIR }}
        submodules: false
        ref: iree-3.0.0rc20241115

    - name: Initalize IREE submodules
      working-directory: ${{ env.IREE_REPO_DIR }}
      run : |
        git submodule update --init --depth 1 -- third_party/benchmark
        git submodule update --init --depth 1 -- third_party/cpuinfo/
        git submodule update --init --depth 1 -- third_party/flatcc
        git submodule update --init --depth 1 -- third_party/googletest
        git submodule update --init --depth 1 -- third_party/hip-build-deps/

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install Python packages
      # TODO: Switch to `pip install -r requirements.txt -e shortfin/`.
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        pip install -r requirements-tests.txt
        pip install -r requirements-iree-compiler.txt
        pip freeze

    - name: Build shortfin (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        mkdir build
        cmake -GNinja \
          -S. \
          -Bbuild \
          -DCMAKE_C_COMPILER=clang-18 \
          -DCMAKE_CXX_COMPILER=clang++-18 \
          -DCMAKE_LINKER_TYPE=LLD \
          -DSHORTFIN_BUNDLE_DEPS=ON \
          -DSHORTFIN_IREE_SOURCE_DIR="${{ env.IREE_REPO_DIR }}" \
          -DSHORTFIN_BUILD_PYTHON_BINDINGS=ON
        cmake --build build --target all
        pip install -v -e build/

    - name: Test shortfin (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        ctest --timeout 30 --output-on-failure --test-dir build
        pytest -s

    - name: Build shortfin (host-only)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        mkdir build-host-only
        # In this configuration, also build static+dynamic in order to verify
        # that path structurally works.
        cmake -GNinja \
          -S. \
          -Bbuild-host-only \
          -DCMAKE_C_COMPILER=clang-18 \
          -DCMAKE_CXX_COMPILER=clang++-18 \
          -DCMAKE_LINKER_TYPE=LLD \
          -DSHORTFIN_IREE_SOURCE_DIR="${{ env.IREE_REPO_DIR }}" \
          -DSHORTFIN_BUILD_PYTHON_BINDINGS=ON \
          -DSHORTFIN_HAVE_AMDGPU=OFF \
          -DSHORTFIN_BUILD_STATIC=ON \
          -DSHORTFIN_BUILD_DYNAMIC=ON
        cmake --build build-host-only --target all
