# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - shortfin - Windows

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci_windows_x64-libshortfin.yml'
      - 'shortfin/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci_windows_x64-libshortfin.yml'
      - 'shortfin/**'

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  IREE_REPO_DIR: ${{ github.workspace }}/iree
  LIBSHORTFIN_DIR: ${{ github.workspace }}/shortfin/

jobs:
  build-and-test:
    name: Build and test
    runs-on: windows-2022

    steps:
    - name: Configure MSVC
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: false

    - name: Checkout IREE repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: iree-org/iree
        path: ${{ env.IREE_REPO_DIR }}
        submodules: false
        ref: candidate-20241104.1068

    - name: Initalize IREE submodules
      working-directory: ${{ env.IREE_REPO_DIR }}
      run : |
        git submodule update --init --depth 1 -- third_party/benchmark
        git submodule update --init --depth 1 -- third_party/cpuinfo/
        git submodule update --init --depth 1 -- third_party/flatcc
        git submodule update --init --depth 1 -- third_party/googletest
        git submodule update --init --depth 1 -- third_party/hip-build-deps/

    - name: Setup Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.3
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install Python packages
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        pip install -r requirements-tests.txt
        pip install -r requirements-iree-compiler.txt
        pip freeze

    - name: Build shortfin (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      shell: bash
      run: |
        mkdir build
        cmake -GNinja \
          -S. \
          -Bbuild \
          -DSHORTFIN_BUNDLE_DEPS=ON \
          -DSHORTFIN_IREE_SOURCE_DIR="${{ env.IREE_REPO_DIR }}" \
          -DSHORTFIN_BUILD_PYTHON_BINDINGS=ON
        cmake --build build --target all
        pip install -v -e build/

    - name: Test shortfin (full)
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        ctest --timeout 30 --output-on-failure --test-dir build
        pytest -s
