# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: PkgCI - shark-ai

on:
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        description: "Id for a workflow run that produced dev packages"
        default: ""

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_shortfin_llm_server:
    name: "Integration Tests - Shortfin LLM Server"
    strategy:
      matrix:
        version: [3.11]
      fail-fast: false
    runs-on: nodai-amdgpu-mi250-x86-64
    defaults:
      run:
        shell: bash
    env:
      PACKAGE_DOWNLOAD_DIR: ${{ github.workspace }}/.packages
      VENV_DIR: ${{ github.workspace }}/.venv
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{matrix.version}}

      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: linux_x86_64_dev_packages
          path: ${{ env.PACKAGE_DOWNLOAD_DIR }}
      - name: Setup venv
        run: |
          ./build_tools/pkgci/setup_venv.py ${VENV_DIR} \
            --artifact-path=${PACKAGE_DOWNLOAD_DIR} \
            --fetch-gh-workflow=${{ inputs.artifact_run_id }}

      - name: Install nightly IREE packages
        run: |
          source ${VENV_DIR}/bin/activate
          uv pip install "git+https://github.com/iree-org/iree-turbine.git#egg=iree-turbine"
          uv pip install -f https://iree.dev/pip-release-links.html --upgrade --pre \
            iree-base-compiler \
            iree-base-runtime

      - name: Run LLM Integration Tests
        run: |
          source ${VENV_DIR}/bin/activate
          pytest -v app_tests/integration_tests/llm/shortfin --log-cli-level=INFO
